### ISSUE TITLE
Create a switch-case application

### ISSUE THREAD

**Issue by HaseebKhanYT** [HaseebKhanYT/DataStructures#1]
I have written the data structures of stack, queue, etc.

while checking if it works I have just called respective functions to test the code.

I want someone to create a Switch-Case application to make these data structures user friendly.

- [x] Make the DynamicArray.cpp User Friendly.

**Comment by AdityaVSM** [comment]
Shall I work on this?

**Comment by HaseebKhanYT** [comment]
> Shall I work on this?

Sure!

**Comment by AdityaVSM** [comment]
I've created PR. Do check it and merge. Suggest edits if any.
